version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: console_shop_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - console_shop_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.2.7-alpine
    container_name: console_shop_redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - console_shop_redis_data:/data

  kafka:
    image: bitnami/kafka:3.7
    container_name: console_shop_kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@${KAFKA_HOST}:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - console_shop_kafka_data:/bitnami/kafka
    env_file:
      - .env

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: console_shop_kafka_ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_HOST}:9092
    env_file:
      - .env

volumes:
  console_shop_postgres_data:
  console_shop_redis_data:
  console_shop_kafka_data:
